header: "<p>(logo??)<br />\r\nCompany Name/Store#<br />\r\nAddress line 1<br />\r\nAddress line 2<br />\r\nPhone #</p>\r\n"
footer: "<p>Thanks for shopping at CompanyName!<br />\r\nReturn Policy --<br />\r\nExchange Policy --<br />\r\nCompany Motto<br />\r\nWebsite --<br />\r\n<br />\r\n(optional)<br />\r\nVisit our website for a chance to --</p>\r\n"
header_format: basic_html
footer_format: basic_html
_core:
  default_config_hash: Z68G6crRW4T2dDSCo8tCO9NTcZiIFg8ZwNaUkeQBt_s
